# search (搜索)
# see https://butterfly.js.org/posts/ceeb73f/#搜索系統
# --------------------------------------
# Algolia search
algolia_search:
  enable: false
  hits:
    per_page: 6

local_search:
  enable: true
  preload: false
  CDN:


# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    - <link rel="stylesheet" href="/css/head.css?v1">
  bottom:
    # - <script src="xxxx"></script>



